# Kubernetes
---
apiVersion: v1
kind: Service
metadata:
  name: stackage-server-prod
  labels:
    app: stackage-server-prod
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: http
  type: ClusterIP
  selector:
    app: stackage-server-prod
