# Kubernetes
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: stackage-server-prod-v0
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: stackage-server-prod
        version: v0
    spec:
      containers:
      - name: stackage-server
        image: fpco/stackage-server:prod
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3000
        command: ["stackage-server"]
        workingDir: /app
        env:
        - name: APPROOT
          value: "https://www.stackage.org"
