resolver: lts-3.9
extra-deps:
    - these-0.6.1.0
    - barrier-0.1.0
image:
    container:
        name: snoyberg/stackage-server
        base: fpco/stack-run
        add:
            config: /app/config
            static: /app/static
