resolver: lts-9.13
packages:
- .
- location:
    git: https://github.com/chrisdone/tagstream-conduit.git
    commit: bacd7444596b2391b0ac302ad649b994b258d271
  extra-dep: true
- location:
    git: https://github.com/commercialhaskell/all-cabal-metadata-tool
    commit: ea541be73238a5ce14ad26f4e2a94e63981242a4
  extra-dep: true
extra-deps:
- barrier-0.1.1
- spoon-0.3.1
