resolver: lts-5.15
packages:
- .
- location:
    git: https://github.com/ndmitchell/hoogle.git
    commit: ca42c4ce3af1c1ae7d413de242063ca1f682d3ff
  extra-dep: true
image:
    container:
        name: fpco/stackage-server
        base: fpco/stack-run
        add:
            config: /app/config
            static: /app/static
