exec: ../dist/build/stackage-server/stackage-server
args:
    - production
host: www.stackage.org

redirects:
    - from: stackage.org
      to: www.stackage.org

postgres: true

# Use the following to automatically copy your bundle upon creation via `yesod
# keter`. Uses `scp` internally, so you can set it to a remote destination
copy-to: ubuntu@www.stackage.org:/opt/keter/incoming
