stanzas:
- type: webapp
  exec: ../dist/build/stackage-server/stackage-server
  args:
    - production
  env:
    STACKAGE_CABAL_LOADER: "0"
  host: www.stackage.org
copy-to: fpuser@www.stackage.org:/var/opt/keter/incoming
