Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://localhost:3000"
  hackage-root: http://hackage.haskell.org/packages/archive

Development:
  <<: *defaults
  blob-store: file:dev-blob-store

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  #approot: "http://www.example.com"
  <<: *defaults
