Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://localhost:3000"
  force-ssl: false

Development:
  <<: *defaults
  dev-download: true

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "https://www.stackage.org"
  force-ssl: true
  <<: *defaults
